version: '4.2'

services:
  pg_master:
    image: postgres
    container_name: pg_master
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: master_user
      POSTGRES_DB: testDB
    volumes:
      - ./init-db/master-init:/docker-entrypoint-initdb.d  # Initial SQL scripts
      - ./init-db/scripts:/scripts  # Scripts for post-restart actions
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "master_user", "-d", "testDB"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  pg_replica:
    image: postgres
    container_name: pg_replica
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: replica_user
      POSTGRES_DB: testDB
    volumes:
      - ./init-db/replica-init:/docker-entrypoint-initdb.d
    depends_on:
      pg_master:
        condition: service_healthy  # Wait for pg_master to be healthy
